function solution_id = catalog_insert_solution(db, run_id, model_version, P, meta)
%CATALOG_INSERT_SOLUTION Insert one solutions row (ok/fail/reject).
% Required meta fields:
%   meta.status ('ok'|'fail'|'reject')
% Optional fields:
%   seed_hash, delta_path_hash, branch_tag, parent_solution_id
%   label, energy_E, pressure_P, bc_max, de_max, mesh_n, n_refines, wall_time_s
%   fail_class, fail_msg, is_best (0/1)

    solution_id = db_transaction(db, @(db_) txn(db_, run_id, model_version, P, meta));
end

function solution_id = txn(db, run_id, model_version, P, meta)
    param_hash = catalog_ensure_param_point(db, model_version, P);

    solution_id = new_uuid();
    created_at = iso_utc(datetime('now','TimeZone','UTC'));

    % Defaults
    status  = string(meta.status);
    is_best = get(meta,'is_best',0);

    sql = "INSERT INTO solutions(" + ...
          "solution_id,run_id,param_hash,seed_hash,delta_path_hash,branch_tag,parent_solution_id," + ...
          "status,is_best,fail_class,fail_msg,label,energy_E,pressure_P,bc_max,de_max,mesh_n,n_refines,wall_time_s,created_at) VALUES (" + ...
          sql_lit(solution_id) + "," + sql_lit(run_id) + "," + sql_lit(param_hash) + "," + ...
          sql_lit_or_null(get(meta,'seed_hash',[])) + "," + ...
          sql_lit_or_null(get(meta,'delta_path_hash',[])) + "," + ...
          sql_lit_or_null(get(meta,'branch_tag',[])) + "," + ...
          sql_lit_or_null(get(meta,'parent_solution_id',[])) + "," + ...
          sql_lit(status) + "," + sql_lit(is_best) + "," + ...
          sql_lit_or_null(get(meta,'fail_class',[])) + "," + ...
          sql_lit_or_null(get(meta,'fail_msg',[])) + "," + ...
          sql_lit_or_null(get(meta,'label',[])) + "," + ...
          sql_lit_or_null(get(meta,'energy_E',[])) + "," + ...
          sql_lit_or_null(get(meta,'pressure_P',[])) + "," + ...
          sql_lit_or_null(get(meta,'bc_max',[])) + "," + ...
          sql_lit_or_null(get(meta,'de_max',[])) + "," + ...
          sql_lit_or_null(get(meta,'mesh_n',[])) + "," + ...
          sql_lit_or_null(get(meta,'n_refines',[])) + "," + ...
          sql_lit_or_null(get(meta,'wall_time_s',[])) + "," + ...
          sql_lit(created_at) + ");";

    db_exec(db, sql);

    % If this solution is marked best, unset any other best for this param_hash
    if is_best == 1
        % Because of partial UNIQUE index, this must be consistent.
        db_exec(db, "UPDATE solutions SET is_best=0 WHERE param_hash=" + sql_lit(param_hash) + ...
                    " AND solution_id<>" + sql_lit(solution_id) + ";");
    end
end

function v = get(S, k, def)
    if isstruct(S) && isfield(S,k), v = S.(k); else, v = def; end
end

function s = sql_lit_or_null(x)
    if isempty(x), s = "NULL"; else, s = sql_lit(x); end
end
