% -------------------------------------------------------------------------
% EXTRACTED HELPER for "makeCell"
%   - Source: sim_driver_quad_tree_full.m
%   - Extracted: 2025-10-11 11:50:11
%   - Sub-helpers (nested functions) are retained in this file.
% -------------------------------------------------------------------------

function C = makeCell(a1, a2, b1, b2, depth)
    % A quadtree cell covering [a1,a2] x [b1,b2].
    C = struct( ...
        'a1',a1,'a2',a2, 'b1',b1,'b2',b2, ...
        'depth',depth, ...
        'corners', [a1 b1; a2 b1; a2 b2; a1 b2], ... % [SW; SE; NE; NW]
        'cornerSolved', false(4,1), ...
        'cornerKey', strings(4,1), ...
        'cornerLabel', nan(4,1), ...
        'cornerEnergy', nan(4,1), ...
        'cornerPressure', nan(4,1), ...
        'isUniform', false, ...
        'mixedEdges', zeros(0,2) ... % pairs of corner indices with differing labels
    );
end