function C = makeCell(bounds, depth)
    if nargin < 2
        depth = 0; % Default depth if not provided
    end
    % A quadtree cell covering [a1,a2] x [b1,b2].
    H1 = bounds(1,:); H2 = bounds(2,:);
    SW = [H1(1) H2(1)]; SE = [H1(2) H2(1)];
    NE = [H1(2) H2(2)]; NW = [H1(1) H2(2)];
    C = struct( ...
        'depth',depth, ...
        'corners', [SW; SE; NE; NW], ...
        'cornerSolved', false(4,1), ...
        'cornerKey', strings(4,1), ...
        'cornerLabel', nan(4,1), ...
        'cornerEnergy', nan(4,1), ...
        'cornerPressure', nan(4,1), ...
        'isUniform', false, ...
        'mixedEdges', zeros(0,2) ... % pairs of corner indices with differing labels
    );
end